---
- hosts: ipa-server
  name: Building IPA server for lab
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - common
    - ipa-server

- hosts: ipa-client
  name: Building IPA clients for lab
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - common
    - ipa-client
